/**
 * Account Routes (Self-service)
 * ============================================
 *
 * Endpoints for logged-in users to manage their own account.
 *
 * ENDPOINTS:
 *   GET    /account         - Get current user's account info
 *   PUT    /account         - Update username/password
 *   POST   /account/api-key - Generate API key
 *   DELETE /account/api-key - Revoke API key
 */

const express = require('express');
const router = express.Router();
const auth = require('../auth');
const { users, logs } = require('../db');

router.get('/', auth.requireAuth, (req, res) => {
  try {
    const user = users.getById(req.user.id);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    const response = {
      id: user.id,
      username: user.username,
      isAdmin: !!user.is_admin,
      hasApiKey: !!user.api_key,
      createdAt: user.created_at,
      lastLogin: user.last_login
    };

    if (user.api_key) {
      response.apiKeyLastFour = user.api_key_last_four;
      response.apiKeyCreatedAt = user.api_key_created_at;
    }

    res.json(response);
  } catch (err) {
    console.error('Error getting account:', err);
    res.status(500).json({ error: 'Failed to get account info' });
  }
});

router.put('/', auth.requireAuth, async (req, res) => {
  const { username, currentPassword, newPassword } = req.body;
  const userId = req.user.id;

  try {
    const user = users.getByUsername(req.user.username);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    // Require current password for any account modification
    if (!currentPassword) {
      return res.status(400).json({ error: 'Current password is required' });
    }
    if (!(await users.verifyPassword(user, currentPassword))) {
      return res.status(401).json({ error: 'Current password is incorrect' });
    }

    const updates = {};

    if (username && username !== user.username) {
      const existing = users.getByUsername(username);
      if (existing) {
        return res.status(409).json({ error: 'Username already taken' });
      }
      if (username.length < 3) {
        return res.status(400).json({ error: 'Username must be at least 3 characters' });
      }
      updates.username = username;
    }

    if (newPassword) {
      if (newPassword.length < 8) {
        return res.status(400).json({ error: 'New password must be at least 8 characters' });
      }
      updates.password = newPassword;
    }

    if (Object.keys(updates).length === 0) {
      return res.status(400).json({ error: 'No changes provided' });
    }

    await users.update(userId, updates);
    logs.add('info', `Account updated by user: ${user.username}`, userId);

    res.json({ success: true, username: updates.username || user.username });
  } catch (err) {
    console.error('Error updating account:', err);
    res.status(500).json({ error: 'Failed to update account' });
  }
});

router.post('/api-key', auth.requireAuth, (req, res) => {
  const userId = req.user.id;

  try {
    const user = users.getById(userId);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    const hadExistingKey = !!user.api_key;
    const result = users.generateApiKey(userId);
    const { apiKey, lastFour, createdAt } = result;
    const clientIP = auth.getClientIP(req);

    const logMessage = hadExistingKey
      ? `API key regenerated by user: ${user.username} (ending in ...${lastFour}) from IP: ${clientIP}`
      : `API key generated by user: ${user.username} (ending in ...${lastFour}) from IP: ${clientIP}`;
    logs.add('info', logMessage, userId);

    res.json({ apiKey, lastFour, createdAt });
  } catch (err) {
    console.error('Error generating API key:', err);
    res.status(500).json({ error: 'Failed to generate API key' });
  }
});

router.delete('/api-key', auth.requireAuth, (req, res) => {
  const userId = req.user.id;

  try {
    const user = users.getById(userId);
    if (!user) {
      return res.status(404).json({ error: 'User not found' });
    }

    const lastFour = user.api_key_last_four || 'unknown';
    users.revokeApiKey(userId);
    const clientIP = auth.getClientIP(req);
    const logMessage = `API key revoked by user: ${user.username} (was ending in ...${lastFour}) from IP: ${clientIP}`;
    logs.add('info', logMessage, userId);

    res.json({ success: true });
  } catch (err) {
    console.error('Error revoking API key:', err);
    res.status(500).json({ error: 'Failed to revoke API key' });
  }
});

module.exports = router;
